spring.application.name=Civilens
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.config.import=optional:file:../.env[.properties]
# Frontend URL
app.frontend.url=${APP_FRONTEND_URL}
# Scheme-engine API
app.scheme-engine.base-url=${APP_SCHEME_ENGINE_BASE_URL}
app.scheme-engine.vector-search-endpoint=${APP_SCHEME_ENGINE_VECTOR_SEARCH_ENDPOINT}
app.scheme-engine.connect-timeout-ms=${APP_SCHEME_ENGINE_CONNECT_TIMEOUT_MS}
app.scheme-engine.read-timeout-ms=${APP_SCHEME_ENGINE_READ_TIMEOUT_MS}
